repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: trailing-whitespace
    - id: mixed-line-ending
    - id: end-of-file-fixer
    - id: debug-statements

  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black src tests
        language: python
        types_or: [python, pyi]

  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: poetry run ruff check src tests --fix
        language: python
        pass_filenames: false
        always_run: true

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy --package tests --package pyheat1d
        language: python
        pass_filenames: false
        always_run: true

  - repo: local
    hooks:
      - id: linter
        name: linter
        entry: poetry run ruff check src tests
        language: python
        pass_filenames: false
        always_run: true


  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: python
        pass_filenames: false
        always_run: true
